optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0005)
checkpoint_config = dict(by_epoch=False, interval=60000)
evaluation = dict(interval=400, metric=['mDice', 'mFscore', 'mIoU'], pre_eval=True, save_best='mDice', rule='greater')
optimizer_config = dict()
lr_config = dict(policy='poly', power=0.9, min_lr=1e-4, by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=60000)
